export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_MY_LIST_REQUEST = "ORDER_MY_LIST_REQUEST";
export const ORDER_MY_LIST_SUCCESS = "ORDER_MY_LIST_SUCCESS";
export const ORDER_MY_LIST_FAIL = "ORDER_MY_LIST_FAIL";
export const ORDER_MY_LIST_RESET = "ORDER_MY_LIST_RESET";

export const ORDER_LISTS_REQUEST = "ORDER_LISTS_REQUEST";
export const ORDER_LISTS_SUCCESS = "ORDER_LISTS_SUCCESS";
export const ORDER_LISTS_FAIL = "ORDER_LISTS_FAIL";
export const ORDER_LISTS_RESET = "ORDER_LISTS_RESET";

export const ORDER_UPDATE_DELIVER_REQUEST = "ORDER_UPDATE_DELIVER_REQUEST";
export const ORDER_UPDATE_DELIVER_SUCCESS = "ORDER_UPDATE_DELIVER_SUCCESS";
export const ORDER_UPDATE_DELIVER_FAIL = "ORDER_UPDATE_DELIVER_FAIL";
export const ORDER_UPDATE_DELIVER_RESET = "ORDER_UPDATE_DELIVER_RESET";
