export const PRODUCT_TRENDING_REQUEST = "PRODUCT_TRENDING_REQUEST";
export const PRODUCT_TRENDING_SUCCESS = "PRODUCT_TRENDING_SUCCESS";
export const PRODUCT_TRENDING_FAIL = "PRODUCT_TRENDING_FAIL";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_COUNT_REQUEST = "PRODUCT_COUNT_REQUEST";
export const PRODUCT_COUNT_SUCCESS = "PRODUCT_COUNT_SUCCESS";
export const PRODUCT_COUNT_FAIL = "PRODUCT_COUNT_FAIL";

export const PRODUCT_ALL_REQUEST = "PRODUCT_ALL_REQUEST";
export const PRODUCT_ALL_SUCCESS = "PRODUCT_ALL_SUCCESS";
export const PRODUCT_ALL_FAIL = "PRODUCT_ALL_FAIL";

