export const PRODUCT_TRENDING_REQUEST = "PRODUCT_TRENDING_REQUEST";
export const PRODUCT_TRENDING_SUCCESS = "PRODUCT_TRENDING_SUCCESS";
export const PRODUCT_TRENDING_FAIL = "PRODUCT_TRENDING_FAIL";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";
