export const REQUEST_SELLER_REQUEST = "USER_SELLER_R_REQUEST";
export const REQUEST_SELLER_SUCCESS = "USER_SELLER_R_SUCCESS";
export const REQUEST_SELLER_FAIL = "USER_SELLER_R_FAIL";
export const REQUEST_SELLER_RESET = "USER_SELLER_R_RESET";