export const REQUEST_SELLER_REQUEST = "REQUEST_SELLER_REQUEST";
export const REQUEST_SELLER_SUCCESS = "REQUEST_SELLER_SUCCESS";
export const REQUEST_SELLER_FAIL = "REQUEST_SELLER_FAIL";
export const REQUEST_SELLER_RESET = "REQUEST_SELLER_RESET";


export const GET_REQUEST_SELLER_REQUEST = "GET_REQUEST_SELLER_REQUEST";
export const GET_REQUEST_SELLER_SUCCESS = "GET_REQUEST_SELLER_SUCCESS";
export const GET_REQUEST_SELLER_FAIL = "GET_REQUEST_SELLER_FAIL";
export const GET_REQUEST_SELLER_RESET = "GET_REQUEST_SELLER_RESET";

export const GET_DESC_REQUEST_SELLER_REQUEST = "GET_DESC_REQUEST_SELLER_REQUEST";
export const GET_DESC_REQUEST_SELLER_SUCCESS = "GET_DESC_REQUEST_SELLER_SUCCESS";
export const GET_DESC_REQUEST_SELLER_FAIL = "GET_DESC_REQUEST_SELLER_FAIL";
export const GET_DESC_REQUEST_SELLER_RESET = "GET_REQUEST_SELLER_RESET";

export const APPROVE_SELLER_REQUEST = "APPROVE_SELLER_REQUEST";
export const APPROVE_SELLER_SUCCESS = "APPROVE_SELLER_SUCCESS";
export const APPROVE_SELLER_FAIL = "APPROVE_SELLER_FAIL";
export const APPROVE_SELLER_RESET = "APPROVE_SELLER_RESET";